grafana:
  adminPassword: "supersecurepassword"
  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - grafana.i-heng.store
  tls:
    - secretName: grafana-tls 
      hosts:
        - grafana.i-heng.store
