replicaCount: 2
image:
  repository: weerapatx/hello-go-api
  tag: "eb6b3e7"
  pullPolicy: IfNotPresent
container:
  name: hello-api
  port: 8080
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  metrics:
    cpu:
      enabled: true
      averageUtilization: 50
    memory:
      enabled: true
      averageUtilization: 70
ingress:
  enabled: true
  host: api.i-heng.store
  clusterIssuer: "letsencrypt"
  tlsSecret: golang-api-tls
services:
  name: golang-api-hello-api
  port: 8080
